"""
Tests for the identity tokenizer (component 2: trainer-side 1-form = 1-token-id path).

Covers: vocab.json round-trip load, the 1:1 form<->id encode/decode invariant, special-token
layout (forms first, specials appended), bos handling, batch encode, and the token_bytes
mask (1 per form, 0 per special) that makes the trainer's bpb equal bits-per-form.

Run: PYTHONPATH=. pytest -q tests/test_identity_tokenizer.py
"""

import json
import os

import pytest

from nanochat.identity_tokenizer import IdentityTokenizer, SPECIAL_TOKENS, get_identity_tokenizer


@pytest.fixture
def vocab_dir(tmp_path):
    # forms intentionally written out of id order to test that load restores by id
    form_to_id = {"w00002": 2, "w00000": 0, "w00001": 1, "w00003": 3}
    d = tmp_path / "cond"
    d.mkdir()
    (d / "vocab.json").write_text(json.dumps(form_to_id))
    return str(d)


def test_load_restores_form_ids(vocab_dir):
    tok = get_identity_tokenizer(vocab_dir)
    assert tok.num_forms == 4
    # forms occupy ids 0..3 in id order regardless of file order
    assert [tok.id_to_token(i) for i in range(4)] == ["w00000", "w00001", "w00002", "w00003"]
    # specials appended after the forms
    assert tok.get_vocab_size() == 4 + len(SPECIAL_TOKENS)
    assert tok.get_bos_token_id() == 4  # first special right after the forms


def test_encode_decode_roundtrip(vocab_dir):
    tok = get_identity_tokenizer(vocab_dir)
    text = "w00001 w00003 w00000 w00002"
    ids = tok.encode(text)
    assert ids == [1, 3, 0, 2]
    assert tok.decode(ids) == text


def test_encode_prepend_bos(vocab_dir):
    tok = get_identity_tokenizer(vocab_dir)
    ids = tok.encode("w00000 w00001", prepend="<|bos|>")
    assert ids[0] == tok.get_bos_token_id()
    assert ids[1:] == [0, 1]
    # prepend by id also works (dataloader passes the int id)
    ids2 = tok.encode("w00000", prepend=tok.get_bos_token_id())
    assert ids2 == [tok.get_bos_token_id(), 0]


def test_batch_encode(vocab_dir):
    tok = get_identity_tokenizer(vocab_dir)
    out = tok.encode(["w00000", "w00001 w00002"], prepend="<|bos|>")
    assert out == [[tok.get_bos_token_id(), 0], [tok.get_bos_token_id(), 1, 2]]


def test_token_bytes_mask(vocab_dir):
    tok = get_identity_tokenizer(vocab_dir)
    tb = tok.token_bytes()
    assert tb.shape[0] == tok.get_vocab_size()
    assert int(tb[: tok.num_forms].sum()) == tok.num_forms      # 1 per form
    assert int(tb[tok.num_forms:].sum()) == 0                   # 0 per special (masked from bpb)
    assert tb.dtype.is_floating_point is False                 # int64 token-byte tensor


def test_non_contiguous_vocab_rejected(tmp_path):
    d = tmp_path / "bad"; d.mkdir()
    (d / "vocab.json").write_text(json.dumps({"a": 0, "b": 2}))  # missing id 1
    with pytest.raises(AssertionError):
        get_identity_tokenizer(str(d))


def test_matches_generator_identity_vocab(tmp_path):
    """The trainer-side IdentityTokenizer must agree with the generator's IdentityVocab on
    form<->id, so a corpus generated by component 1 reloads as the exact same token stream."""
    from nanochat.polysemy import (
        GeneratorConfig, build_default_pcfg, build_sense_inventory, build_sense_form_map,
        generate_sense_corpus, render_documents, write_vocab, _sense_probabilities,
    )
    class_sizes = {"N": 8, "V": 5, "DET": 2, "P": 3}
    pcfg = build_default_pcfg()
    inv = build_sense_inventory(class_sizes)
    sense_docs = generate_sense_corpus(pcfg, inv, num_tokens=4000, min_len=5, max_len=20, seed=0)
    sp = _sense_probabilities(sense_docs, inv.num_senses)
    smap = build_sense_form_map(inv, sp, target_hsw=0.5, overlap="partial")
    docs = render_documents(sense_docs, smap, seed=0)
    write_vocab(smap, str(tmp_path))
    tok = get_identity_tokenizer(str(tmp_path))
    assert tok.num_forms == smap.vocab_size
    for d in docs[:50]:
        assert tok.decode(tok.encode(d)) == d
        for sym in d.split():
            assert sym in tok.stoi
